name = "Qiskit"
uuid = "b9719d41-2062-433c-a3e7-1e25e81db4f5"
authors = ["spencerking <spencerking@users.noreply.github.com>"]
version = "0.1.0"

[deps]
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
